import type { AuditedEntityDto, EntityDto } from '@abp/ng.core';
import type { LoaiVuViec } from '../loai-vu-viec.enum';
import type { LoaiKetQua } from '../loai-ket-qua.enum';
import type { CreateAndUpdateFileAttachmentDto, FileAttachmentDto } from '../file-attachments/models';
import type { BaseListFilterDto } from '../models';
import type { LinhVuc } from '../linh-vuc.enum';

export interface ComplainDto extends AuditedEntityDto<string> {
  maHoSo?: string;
  loaiVuViec: LoaiVuViec;
  tieuDe?: string;
  nguoiDeNghi?: string;
  cccdCmnd?: string;
  ngayCapCccdCmnd?: string;
  noiCapCccdCmnd?: string;
  ngaySinh?: string;
  dienThaoi?: string;
  email?: string;
  diaChiThuongTru?: string;
  diaChiLienHe?: string;
  maTinhTP?: string;
  maQuanHuyen?: string;
  maXaPhuongTT?: string;
  ngayTiepNhan?: string;
  ngayHenTraKQ?: string;
  noiDungVuViec?: string;
  soThua?: string;
  toBanDo?: string;
  dienTich?: string;
  loaiDat?: string;
  diaChiThuaDat?: string;
  tinhThuaDat?: string;
  huyenThuaDat?: string;
  xaThuaDat?: string;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQDII?: string;
  ketQua2?: LoaiKetQua;
  ketQua?: LoaiKetQua;
  fileAttachments: FileAttachmentDto[];
}

export interface CreateComplainDto {
  maHoSo: string;
  loaiVuViec: LoaiVuViec;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  ngayCapCccdCmnd: string;
  noiCapCccdCmnd: string;
  ngaySinh: string;
  dienThaoi: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: string;
  maQuanHuyen: string;
  maXaPhuongTT: string;
  ngayTiepNhan: string;
  ngayHenTraKQ: string;
  noiDungVuViec: string;
  soThua: string;
  toBanDo: string;
  dienTich: string;
  loaiDat: string;
  diaChiThuaDat: string;
  tinhThuaDat: string;
  huyenThuaDat: string;
  xaThuaDat: string;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
}

export interface GetComplainListDto extends BaseListFilterDto {
  loaiVuViec?: LoaiVuViec;
  linhVuc?: LinhVuc;
  ketQua?: LoaiKetQua;
}

export interface UpdateComplainDto extends EntityDto<string> {
  maHoSo: string;
  loaiVuViec: LoaiVuViec;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  ngayCapCccdCmnd: string;
  noiCapCccdCmnd: string;
  ngaySinh: string;
  dienThaoi: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: string;
  maQuanHuyen: string;
  maXaPhuongTT: string;
  ngayTiepNhan: string;
  ngayHenTraKQ: string;
  noiDungVuViec: string;
  soThua: string;
  toBanDo: string;
  dienTich: string;
  loaiDat: string;
  diaChiThuaDat: string;
  tinhThuaDat: string;
  huyenThuaDat: string;
  xaThuaDat: string;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
  listTepDinhKemHoSosDeleted: string[];
  concurrencyStamp?: string;
}
