import type { AuditedEntityDto, EntityDto } from '@abp/ng.core';
import type { LoaiVuViec } from '../loai-vu-viec.enum';
import type { LoaiKhieuNai } from '../loai-khieu-nai.enum';
import type { LoaiKetQua } from '../loai-ket-qua.enum';
import type { CreateAndUpdateFileAttachmentDto, FileAttachmentDto } from '../file-attachments/models';
import type { BaseListFilterDto } from '../models';
import type { LinhVuc } from '../linh-vuc.enum';

export interface ComplainDto extends AuditedEntityDto<string> {
  maHoSo?: string;
  loaiVuViec: LoaiVuViec;
  tieuDe?: string;
  nguoiDeNghi?: string;
  cccdCmnd?: string;
  ngaySinh?: string;
  dienThoai?: string;
  email?: string;
  diaChiThuongTru?: string;
  diaChiLienHe?: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan?: string;
  thoiGianHenTraKQ?: string;
  noiDungVuViec?: string;
  boPhanDangXL?: string;
  soThua?: string;
  toBanDo?: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat?: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  loaiKhieuNai1?: LoaiKhieuNai;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  loaiKhieuNai2?: LoaiKhieuNai;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  ketQua?: LoaiKetQua;
  fileAttachments: FileAttachmentDto[];
  concurrencyStamp?: string;
}

export interface CreateComplainDto {
  maHoSo: string;
  loaiVuViec: LoaiVuViec;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianHenTraKQ: string;
  noiDungVuViec: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  loaiKhieuNai1?: LoaiKhieuNai;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  loaiKhieuNai2?: LoaiKhieuNai;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
}

export interface GetComplainListDto extends BaseListFilterDto {
  maTinhTP?: number;
  maQuanHuyen?: number;
  maXaPhuongTT?: number;
  ngayTiepNhan?: string;
  loaiVuViec?: LoaiVuViec;
  linhVuc?: LinhVuc;
  ketQua?: LoaiKetQua;
}

export interface UpdateComplainDto extends EntityDto<string> {
  maHoSo: string;
  loaiVuViec: LoaiVuViec;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianHenTraKQ: string;
  noiDungVuViec: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  loaiKhieuNai1?: LoaiKhieuNai;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  loaiKhieuNai2?: LoaiKhieuNai;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
  listTepDinhKemHoSosDeleted: string[];
  concurrencyStamp?: string;
}
