import type { LinhVuc } from '../linh-vuc.enum';
import type { LoaiKetQua } from '../loai-ket-qua.enum';
import type { CreateAndUpdateFileAttachmentDto, FileAttachmentDto } from '../file-attachments/models';
import type { AuditedEntityDto, EntityDto } from '@abp/ng.core';
import type { BaseListFilterDto } from '../models';

export interface CreateDenounceDto {
  maHoSo: string;
  linhVuc: LinhVuc;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  noiCapCccdCmnd?: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianTraKQ: string;
  noiDungVuViec: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
}

export interface DenounceDto extends AuditedEntityDto<string> {
  maHoSo?: string;
  linhVuc: LinhVuc;
  tieuDe?: string;
  nguoiDeNghi?: string;
  cccdCmnd?: string;
  ngayCapCccdCmnd?: string;
  noiCapCccdCmnd?: string;
  ngaySinh?: string;
  dienThoai?: string;
  email?: string;
  diaChiThuongTru?: string;
  diaChiLienHe?: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT?: string;
  thoiGianTiepNhan?: string;
  thoiGianHenTraKQ?: string;
  noiDungVuViec?: string;
  boPhanDangXL?: string;
  soThua?: string;
  toBanDo?: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat?: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQDII?: string;
  ketQua2?: LoaiKetQua;
  ketQua?: LoaiKetQua;
  fileAttachments: FileAttachmentDto[];
  concurrencyStamp?: string;
}

export interface GetDenounceListDto extends BaseListFilterDto {
  maTinhTP?: number;
  maQuanHuyen?: number;
  maXaPhuongTT?: number;
  fromDate?: string;
  toDate?: string;
  linhVuc?: LinhVuc;
  ketQua?: LoaiKetQua;
  giaiDoan?: number;
}

export interface UpdateDenounceDto extends EntityDto<string> {
  maHoSo: string;
  linhVuc: LinhVuc;
  tieuDe: string;
  nguoiDeNghi: string;
  cccdCmnd: string;
  noiCapCccdCmnd?: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianHenTraKQ: string;
  noiDungVuViec: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayKhieuNai1?: string;
  ngayTraKQ1?: string;
  thamQuyen1?: string;
  soQD1?: string;
  ketQua1?: LoaiKetQua;
  ngayKhieuNai2?: string;
  ngayTraKQ2?: string;
  thamQuyen2?: string;
  soQD2?: string;
  ketQua2?: LoaiKetQua;
  concurrencyStamp?: string;
}
