import type { LinhVuc } from '../linh-vuc.enum';
import type { LoaiKetQua } from '../loai-ket-qua.enum';
import type { CreateAndUpdateFileAttachmentDto, FileAttachmentDto } from '../file-attachments/models';
import type { AuditedEntityDto, EntityDto } from '@abp/ng.core';
import type { BaseListFilterDto } from '../models';

export interface CreateDenounceDto {
  maHoSo: string;
  linhVuc: LinhVuc;
  tieuDe: string;
  nguoiToCao: string;
  cccdCmnd: string;
  noiCapCccdCmnd?: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianTraKQ: string;
  noiDungVuViec: string;
  nguoiBiToCao: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayGQTC: string;
  nguoiGQTC: string;
  quyerDinhThuLyGQTC: string;
  ngayQDGQTC: string;
  quyetDinhDinhChiGQTC?: string;
  giaHanGQTC1?: string;
  giaHanGQTC2?: string;
  soVBKLNDTC: string;
  ngayNhanTBKQXLKLTC: string;
  ketQua: LoaiKetQua;
  congKhai: boolean;
  fileAttachments: CreateAndUpdateFileAttachmentDto[];
}

export interface DenounceDto extends AuditedEntityDto<string> {
  maHoSo?: string;
  linhVuc: LinhVuc;
  tieuDe?: string;
  nguoiToCao?: string;
  cccdCmnd?: string;
  ngayCapCccdCmnd?: string;
  noiCapCccdCmnd?: string;
  ngaySinh?: string;
  dienThoai?: string;
  email?: string;
  diaChiThuongTru?: string;
  diaChiLienHe?: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan?: string;
  thoiGianHenTraKQ?: string;
  noiDungVuViec?: string;
  nguoiBiToCao?: string;
  boPhanDangXL?: string;
  soThua?: string;
  toBanDo?: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat?: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayGQTC?: string;
  nguoiGQTC?: string;
  quyerDinhThuLyGQTC?: string;
  ngayQDGQTC?: string;
  quyetDinhDinhChiGQTC?: string;
  giaHanGQTC1?: string;
  giaHanGQTC2?: string;
  soVBKLNDTC?: string;
  ngayNhanTBKQXLKLTC?: string;
  ketQua: LoaiKetQua;
  congKhai: boolean;
  fileAttachments: FileAttachmentDto[];
  concurrencyStamp?: string;
}

export interface GetDenounceListDto extends BaseListFilterDto {
  maTinhTP?: number;
  maQuanHuyen?: number;
  maXaPhuongTT?: number;
  fromDate?: string;
  toDate?: string;
  linhVuc?: LinhVuc;
  ketQua?: LoaiKetQua;
  congKhai?: boolean;
}

export interface UpdateDenounceDto extends EntityDto<string> {
  maHoSo: string;
  linhVuc: LinhVuc;
  tieuDe: string;
  nguoiToCao: string;
  cccdCmnd: string;
  noiCapCccdCmnd?: string;
  ngaySinh: string;
  dienThoai: string;
  email?: string;
  diaChiThuongTru: string;
  diaChiLienHe: string;
  maTinhTP: number;
  maQuanHuyen: number;
  maXaPhuongTT: number;
  thoiGianTiepNhan: string;
  thoiGianHenTraKQ: string;
  noiDungVuViec: string;
  nguoiBiToCao: string;
  boPhanDangXL: string;
  soThua: string;
  toBanDo: string;
  dienTich: number;
  loaiDat: number;
  diaChiThuaDat: string;
  tinhThuaDat: number;
  huyenThuaDat: number;
  xaThuaDat: number;
  duLieuToaDo?: string;
  duLieuHinhHoc?: string;
  ghiChu?: string;
  ngayGQTC: string;
  nguoiGQTC: string;
  quyerDinhThuLyGQTC: string;
  ngayQDGQTC: string;
  quyetDinhDinhChiGQTC?: string;
  giaHanGQTC1?: string;
  giaHanGQTC2?: string;
  soVBKLNDTC: string;
  ngayNhanTBKQXLKLTC: string;
  ketQua: LoaiKetQua;
  congKhai: boolean;
  concurrencyStamp?: string;
}
